INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Connacht","Galway","Ap #872-4680 Egestas Rd.","I32 AB01");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Cork","792-4104 Ac Road","I32 AB02");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Ulster","Donegal","Ap #316-4283 Curabitur St.","I32 AB03");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Cork","5045 Auctor Avenue","I32 AB04");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Ulster","Cavan","6798 Vehicula Street","I32 AB05");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Connacht","Galway","Ap #290-1943 Lacus St.","I32 AB06");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Connacht","Leitrim","304 Est. St.","I32 AB07");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Connacht","Galway","Ap #332-4519 Aenean St.","I32 AB08");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Cork","357-1485 Nisl. Road","I32 AB09");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Cork","998-3628 Diam Rd.","I32 EF01");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Connacht","Galway","9751 Lectus St.","I32 EF02");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Kildare","Ap #938-280 Nonummy Rd.","I32 EF03");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Kildare","P.O. Box 591, 2312 Ac St.","I32 EF04");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Cork","9506 Neque. Avenue","I32 EF05");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Cork","Ap #660-3095 Rhoncus Ave","I32 EF06");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Ulster","Monaghan","678-8441 Dui, Rd.","I32 EF07");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Ulster","Monaghan","3973 Ipsum Avenue","I32 EF08");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Connacht","Roscommon","4900 Mauris. Ave","I32 EF09");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","West-Meath","Ap #953-7878 Cras Ave","I32 IJ01");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Cork","627-2399 Dignissim Rd.","I32 IJ02");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Cork","Ap #378-3647 Ornare. Av.","I32 IJ03");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Cork","1897 Metus. Ave","I32 IJ04");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Cork","Ap #914-2148 Risus. Av.","I32 IJ05");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Kildare","P.O. Box 350, 4718 Amet, Rd.","I32 IJ06");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Cork","675-2170 Mus. St.","I32 IJ07");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Kildare","Ap #486-2728 Proin Rd.","I32 IJ08");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Kildare","P.O. Box 414, 605 Aliquam Rd.","I32 IJ09");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Carlow","551-1807 Nonummy Avenue","I32 OP01");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Longford","Ap #190-2184 Auctor Street","I32 OP02");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Ulster","Donegal","Ap #568-5928 Semper Rd.","I32 OP03");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Kildare","7428 Metus. St.","I32 OP04");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Ulster","Cavan","P.O. Box 757, 8002 Eu, Ave","I32 OP05");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Meath","8362 Donec Street","I32 OP06");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Meath","P.O. Box 782, 6132 Urna, Avenue","I32 OP07");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","West-Meath","276-3417 Ipsum Avenue","I32 OP08");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Meath","618-5824 Eu Av.","I32 OP09");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Cork","3431 Integer Rd.","I32 UV01");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Meath","7614 A Ave","I32 UV02");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Limerick","P.O. Box 140, 7134 Dui. St.","I32 UV03");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Connacht","Sligo","8480 Vestibulum Avenue","I32 UV04");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Limerick","822-4298 Mauris Av.","I32 UV05");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Limerick","P.O. Box 296, 7981 Vehicula Road","I32 UV06");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Meath","Ap #417-7788 Aliquam, Av.","I32 UV07");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Connacht","Sligo","Ap #507-7158 Pellentesque Street","I32 UV08");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","West-Meath","676-6551 Mauris Road","I32 UV09");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Wexford","737-8352 Nibh. St.","I32 ST01");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Wexford","3809 Metus. Ave","I32 ST02");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Limerick","9244 Diam Avenue","I32 ST03");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Limerick","782-7434 Magna Rd.","I32 ST04");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Wexford","200-9369 Nunc Rd.","I32 ST05");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Wexford","P.O. Box 271, 5165 Mauris Rd.","I32 ST06");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Kilkenny","Ap #494-9151 Ac St.","I32 ST07");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Wexford","Ap #272-2955 Cras Avenue","I32 ST08");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Connacht","Galway","460-9994 Phasellus Rd.","I32 ST09");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Waterford","8802 Facilisis Ave","I32 ST10");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Tipparary","774-6211 Magna. Road","I32 UV10");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Tipparary","724-6040 Ornare, Avenue","I32 AB10");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Tipparary","Ap #421-1006 Libero. St.","I32 EF10");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Connacht","Mayo","P.O. Box 890, 3036 Placerat, Rd.","I32 IJ10");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Connacht","Mayo","8555 Elit. Street","I32 OP10");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Connacht","Mayo","130-5717 Vehicula St.","I32 QR01");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Wicklow","7321 Parturient Road","I32 QR02");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","Ap #430-8643 Massa. Avenue","I32 QR03");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Tipparary","937-1832 Senectus Ave","I32 QR04");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Clare","P.O. Box 697, 9105 Posuere, Road","I32 QR05");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Wicklow","2548 Lectus St.","I32 QR06");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Waterford","Ap #333-9944 Purus. St.","I32 QR07");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","P.O. Box 167, 7841 Ipsum. Road","I32 QR08");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","P.O. Box 966, 8565 Laoreet, Rd.","I32 QR09");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","Ap #413-903 Ligula. Rd.","I32 QR10");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Wicklow","P.O. Box 728, 6220 Mus. Rd.","I32 LM01");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","Ap #150-8796 Fringilla Av.","I32 LM02");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Kerry","P.O. Box 227, 118 Varus Avenue","I32 LM03");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","3672 Orci. St.","I32 LM04");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Kerry","Ap #912-8268 Augue St.","I32 LM05");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","Ap #664-5904 Dolor. Av.","I32 LM06");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Ulster","Donegal","P.O. Box 667, 333 Dolor Rd.","I32 LM07");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","P.O. Box 326, 5313 Fames Rd.","I32 LM08");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","384-845 Non, Avenue","I32 LM09");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","6988 Mauris, Street","I32 LM10");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Munster","Clare","7750 Ut Ave","I32 WX01");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","377-6562 Nec Av.","I32 WX02");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","322-8195 Nam Rd.","I32 WX03");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","1145 Neque. Rd.","I32 WX04");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","Ap #202-9660 Pellentesque Ave","I32 WX05");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","Ap #863-8975 Ac St.","I32 WX06");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","P.O. Box 495, 1987 Nunc Ave","I32 WX07");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","Ap #619-7908 Malesuada Street","I32 WX08");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Wicklow","940-3682 Sit Rd.","I32 WX09");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","Ap #681-7017 Purus Rd.","I32 WX10");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","Ap #839-5692 Magnis St.","I32 BC01");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","Ap #342-267 Pellentesque St.","I32 BC02");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Offaly","Ap #473-1662 Ornare, Avenue","I32 BC03");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Laois","Ap #309-5596 Metus. St.","I32 BC04");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","Ap #808-7662 Porttitor Avenue","I32 BC05");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","Ap #392-4542 Rutrum St.","I32 BC06");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","P.O. Box 297, 6078 Arcu. St.","I32 BC07");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Dublin","880-2481 Imperdiet Avenue","I32 BC08");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Kilkenny","581-765 Amet Rd.","I32 BC09");
INSERT INTO `Residence` (`Country`,`Province`, `County`,`Street`,`Eir_Code`) VALUES ("Ireland","Leinster","Kilkenny","730 Convallis Ave","I32 BC10");
